program: train.py
name: train_flower_d5-p12-r2_decision_st-far_n10000
method: grid
metric:
  name: eval/decision_accuracy
  goal: maximize
parameters:
  lr: 
    values: [1e-4, 3e-4, 1e-3, 3e-3]
  weight_decay:
    values: [0.1, 0.01]
  seed:
    values: [42, 43]
  lr_scheduler_type:
    values: [cosine, linear]
  teach:
    values: [dfs, optimal] # [walk-10, walk-14, walk-18, walk-22, walk-26, walk-30, walk-34, walk-38, walk-42, walk-46, walk-50, walk_mix-10, walk_mix-14, walk_mix-18, walk_mix-22, walk_mix-26, walk_mix-30, walk_mix-34, walk_mix-38, walk_mix-42, walk_mix-46, walk_mix-50, dfs]
  # num_train:
  #   values: [100000, 200000, 300000, 400000, 500000]