seed: 42
teach: walk-20
num_train: 100000
num_epochs: 50 
num_node_tokens: 102
context_length: 1000
batch_size: 500
eval_steps: 100
log_steps: 100
save_steps: 500
gradient_accumulation_steps: 1
weight_decay: 0.1
warmup_steps: 4000
lr: 0.0003
lr_scheduler_type: cosine
save_total_limit: 5
model_config: configs/model_config.yaml
output_dir: 
data_dir: 
train_file: 
val_file: 
wandb_config:
  project: bepatient
  entity: 
  dir: 

