seed: 42
task: cycle_decision
teach: optimal
num_train: 10000
num_train_epochs: 500
num_node_tokens: 8
context_length: 100
batch_size: 1000
eval_steps: 100
log_steps: 100
save_steps: 500
gradient_accumulation_steps: 1
weight_decay: 0.1
warmup_steps: 100
lr: 0.001
lr_scheduler_type: linear
save_total_limit: 5
model_config: configs/model_config.yaml
output_dir: /work/hdd/bbjr/pmirtaheri/bepatient/output_dir
data_dir: /work/hdd/bbjr/pmirtaheri/bepatient/data_dir
train_file: train_cycle_decision_n100000.json
val_file: val_cycle_decision_n5000.json
wandb:
  project: bepatient
  entity: seyedparsa
  dir: /work/hdd/bbjr/pmirtaheri/bepatient/wandb
