# depth 2 small
# sweep_name: delta_flower_d3-s3-l5-b3_t6e6
# sweep_ids: [pppsracl]
# num_node_tokens: 62
# context_length: 300
# val_file: val_flower_d3-s3-l5-b3_decision_st-far_n5000.json

# depth 2 large
# sweep_name: delta_flower_d3-s3-l5-b3_t10e6
# sweep_ids: [xvy8kfg5, lnhz7bwy]
# num_node_tokens: 62
# context_length: 300
# val_file: val_flower_d3-s3-l5-b3_decision_st-far_n5000.json

# depth 4:
sweep_name: flower_d3-s3-l5-b3_t10e6_hl4
sweep_ids: [al4rkv0a, rx4g6o6l, 1u3lpsj8, 25mfuxuy, 1hfglhlw] # 2no8rcys, lcc81sdz]
num_node_tokens: 62
context_length: 400
play_file: train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
val_file: val_flower_d3-s3-l5-b3_decision_st-far_n5000.json
path-play-1: path-play-1_n97224_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
path-play-2: path-play-2_n174493_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
path-play-3: path-play-3_n287998_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
path-play-4: path-play-4_n362161_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
path-play-5: path-play-5_n407049_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
# path-play-2: path-play-2_n180351_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
# path-play-3: path-play-3_n249928_on_train_flower_d3-s3-l5-b3_decision_st-far_n500000.json
