# depth 2
# sweep_name: delta_flower_d4-s3-l5-b3_t11e6
# sweep_ids: [80si7bxe]
# num_node_tokens: 82
# context_length: 400
# val_file: val_flower_d4-s3-l5-b3_decision_st-far_n5000.json

#depth 4
sweep_name: flower_d4-s3-l5-b3_t11.5e6_hl4
sweep_ids: [e1aatftd, saik6dmb, nxyqypcy, yf8igfku, 1uot0cjv] # r7zlsect, vn8nwp8d]
num_node_tokens: 82
context_length: 400
play_file: train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
val_file: val_flower_d4-s3-l5-b3_decision_st-far_n5000.json
path-play-1: path-play-1_n79700_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
path-play-2: path-play-2_n145205_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
path-play-3: path-play-3_n205619_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
# path-play-4: path-play-4_n273256_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
path-play-4: path-play-4_g_n341930_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
path-play-5: path-play-5_n330683_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
# path-play-2: path-play-2_n127731_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json
# path-play-3: path-play-3_n179108_on_train_flower_d4-s3-l5-b3_decision_st-far_n500000.json